spring.application:
  name: oris_spring

logging:
  enabled: true

info:
  app:
    name: Learn Spring
    version: 0.2.0

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application: Learn Spring
  datasource:
    url: 'jdbc:${DATABASE_URL}'
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver